# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pr:
- none

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    pip install -r requirements.txt
    behave **/
  displayName: 'Running MoneyHelper DTT BDD on lambdatest'
